backend:
  name: github
  repo: gomezfx/nazuks-site
media_folder: static/assets
public_folder: assets
collections:
  - name: writing
    label: Writing
    folder: src/pages/writing
    create: true
    fields:
      - { name: image, label: Image, widget: image }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: type, label: Type }
      - { name: publication, label: Publication }
      - { name: link, label: Link }
  - name: video
    label: Video
    folder: src/pages/video
    create: true
    fields:
      - { name: image, label: Image, widget: image }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: type, label: Type }
      - { name: role, label: Role }
      - { name: link, label: Link }
  - name: fashion
    label: Fashion
    folder: src/pages/fashion
    create: true
    fields:
      - { name: image, label: Image, widget: image }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: type, label: Type }
      - { name: publication, label: Publication }
      - { name: role, label: Role }
      - { name: link, label: Link }