backend:
  name: github
  repo: gomezfx/nazuks-site
media_folder: static/assets
public_folder: assets
collections:
  - name: writing
    label: Writing
    folder: src/pages/writing
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }